import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Hi!': 'Hi',
          'Welcome to CyberSecure': 'WELCOME TO CyberSecure',
          'Financial Fraud': 'Financial Fraud',
          'Data ': 'Data',
          'Breach': 'Breach',
          'Insurance ': 'Insurance',
          'Fraud': 'Fraud',
          'Social Media ': 'Social Media',
          'Crimes': 'Crimes',
          'Women/Child': 'Women/Child',
          'Crypto ': 'Crypto',
          'Scams': 'Scams',
          'job Fraud': 'Job Fraud',
          'Loan Fraud': 'Loan Fraud',
          'Denial Of ': 'Denial Of',
          'Services': 'Services',
          'Online ': 'Online',
          'Shopping Fraud': 'Shopping Fraud',
          'SIM Swapping ': 'SIM Swapping',
          'Customer ': 'Customer',
          'Care Fraud': 'Care Fraud',
          'E-Commerce ': 'E-Commerce',
          'Related Fraud': 'Related Fraud',
          'Tower Installation ': 'Tower Installation',
          'Ransomware ': 'Ransomware',
          'Attack': 'Attack',
          'Phishing': 'Phishing',
          'Latest Scam Trends': 'Latest Scam Trends',
          'Home': 'Home',
          'Analysis': 'Analysis',
          'Complain': 'Complain',
          'Profile': 'Profile',
          'See All': 'See All',
          'Personal Info': 'Personal Info',
          'Resolved Cases': 'Resolved Cases',
          'Active Cases': 'Active Cases',
          'Language': 'Language',
          'Customer Support': 'Customer Support',
          'Logout': 'Logout',
          'Lottery/Prize ': 'Lottery/Prize',
        },
        'hi_IN': {
          'Hi!': 'नमस्ते',
          'Welcome to CyberSecure': 'साइबर सिक्योर में आपका स्वागत है',
          // 'message':'WELCOME TO CyberSecure',
          'Financial Fraud': 'वित्तीय धोखाधड़ी',
          'Data ': 'डेटा',
          'Breach': 'भंग',
          'Insurance ': 'बीमा',
          'Social Media ': 'सोशल मीडिया',
          'Crimes': 'अपराध',
          'Women/Child': 'महिला/बच्चा',
          'Crypto ': 'क्रिप्टो',
          'Scams': 'घोटाले',

          'job Fraud': 'नौकरी धोखाधड़ी',
          'Loan Fraud': 'ऋण धोखाधड़ी',
          'Denial Of': 'सेवा की',
          'Services': 'मनाई',
          'Online ': 'ऑनलाइन',
          'Shopping Fraud': 'शॉपिंग धोखाधड़ी',
          'SIM Swapping ': 'सिम स्वैपिंग',
          'Fraud': 'धोखाधड़ी',
          'Customer ': 'ग्राहक',
          'Care Fraud': 'वित्तीय धोखाधड़ी',
// Data BreachCare Fraud',
          'E-Commerce ': 'ई-कॉमर्स',
          'Related Fraud': 'संबंधित धोखाधड़ी',
          'Tower Installation ': 'टावर स्थापना',
          'Ransomware ': 'रैंसमवेयर',
          'Attack': 'हमला',
          'Phishing': 'फ़िशिंग',
          'Latest Scam Trends': 'नवीनतम घोटाले के रुझान',
          'Home': 'घर',
          'Analysis': 'विश्लेषण',
          'Complain': 'शिकायत',
          'Profile': 'प्रोफ़ाइल',
          'See All': 'सभी देखें',
          'Personal Info': 'व्यक्तिगत जानकारी',
          'Resolved Cases': 'सुलझे हुए मामले',
          'Active Cases': 'एक्टिव केस',
          'Language': 'भाषा',
          'Customer Support': 'ग्राहक सहेयता',
          'Logout': 'लॉगआउट',
          'Lottery/Prize ': 'लॉटरी/पुरस्कार',
        }
      };
}
